/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class ChucVu extends javax.swing.JPanel {

    /**
     * Creates new form ChucVu
     */
    DefaultTableModel tbn = new DefaultTableModel();
    public ChucVu() throws SQLException {
        initComponents();
        loadDataChucVu();
    }
    public  void loadDataChucVu() throws SQLException{
        {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from ChucVu");
            Object[] obj = new Object[]{"Mã ", "Tên Chức Vụ"};
            DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
            tblChucVu.setModel(tableModel);
            try {
                while (rs.next()) {
                    Object[] item = new Object[2];
                    item[0] = rs.getInt("MaChucVu");
                    item[1] = rs.getString("TenChucVu");
                    tableModel.addRow(item);
                }
   
        } catch (SQLException ex) {
                System.out.println(ex.toString());
        }
        }
    }
    private void loadDataChucVuNhanVien(String text) throws SQLException {
        Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from NhanVien,ChucVu where NhanVien.MaChucVu=ChucVu.MaChucVu and ChucVu.MaChucVu="+text );
            Object[] obj = new Object[]{"Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ"};
            DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
            tblChucVuNhanVien.setModel(tableModel);

            try {
                while (rs.next()) {
                    Object[] item = new Object[3];
                    item[0] = rs.getInt("MaNhanVien");
                    item[1] = rs.getString("TenNhanVien");
                    item[2] = rs.getString("TenChucVu");
                    tableModel.addRow(item);
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaChucVu = new javax.swing.JTextField();
        txtTenChucVu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnXoaChucVu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChucVuNhanVien = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã Chức Vụ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tên Chức Vụ:");

        txtMaChucVu.setEditable(false);
        txtMaChucVu.setBackground(new java.awt.Color(204, 204, 204));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 102, 102));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 102, 102));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 102, 102));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Refresh_16x16.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnXoaChucVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaChucVu.setForeground(new java.awt.Color(0, 102, 102));
        btnXoaChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete_16x16.png"))); // NOI18N
        btnXoaChucVu.setText("Xóa Nếu Rỗng");
        btnXoaChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnXoaChucVu)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(btnXoaChucVu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblChucVu.setBackground(new java.awt.Color(255, 204, 204));
        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã Chức Vụ", "Tên Chức Vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucVu);
        if (tblChucVu.getColumnModel().getColumnCount() > 0) {
            tblChucVu.getColumnModel().getColumn(0).setMinWidth(30);
            tblChucVu.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblChucVu.getColumnModel().getColumn(0).setMaxWidth(30);
            tblChucVu.getColumnModel().getColumn(1).setMinWidth(90);
            tblChucVu.getColumnModel().getColumn(1).setPreferredWidth(90);
            tblChucVu.getColumnModel().getColumn(1).setMaxWidth(90);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chức Vụ");

        tblChucVuNhanVien.setBackground(new java.awt.Color(255, 204, 204));
        tblChucVuNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhân Viên", "Tên Nhân Viên", "Tên Chức Vụ"
            }
        ));
        jScrollPane2.setViewportView(tblChucVuNhanVien);
        if (tblChucVuNhanVien.getColumnModel().getColumnCount() > 0) {
            tblChucVuNhanVien.getColumnModel().getColumn(0).setMinWidth(30);
            tblChucVuNhanVien.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblChucVuNhanVien.getColumnModel().getColumn(0).setMaxWidth(30);
            tblChucVuNhanVien.getColumnModel().getColumn(1).setMinWidth(90);
            tblChucVuNhanVien.getColumnModel().getColumn(1).setPreferredWidth(90);
            tblChucVuNhanVien.getColumnModel().getColumn(1).setMaxWidth(90);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nhân Viên Chức Vụ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();
        if(txtMaChucVu.getText().equals("")){
        if(txtTenChucVu.getText().equals("")){
            sb.append("Hãy nhập tên chức vụ ! \n");
            txtTenChucVu.requestFocus();
        }
        else{
        try {
             Connect a = new Connect();
             Connection conn = a.getConnection();
             PreparedStatement ps = conn.prepareStatement("insert into ChucVu(TenChucVu) values(?) ");
             
             ps.setString(1,txtTenChucVu.getText());
             int chk = ps.executeUpdate();
             if(chk>0){
                 sb.append("Thêm thành công!");
                 loadDataChucVu();
             }
        } catch (SQLException ex) {
             System.out.println(ex.toString());
        }
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return;
        }
        }
        else{
            sb.append("vui lòng nhấn Reset trước khi thêm! \n");
        }
                if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return;
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaChucVuActionPerformed
       try {
            StringBuilder sb = new StringBuilder();
            if(txtMaChucVu.getText().equals("")){
                    sb.append("Hãy click vào Chức Vụ bạn muốn xóa \n");
                }
            else{
            if((tblChucVuNhanVien.getRowCount())<=0){
              
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pc = conn.prepareStatement("delete ChucVu where MaChucVu=?");
            pc.setString(1, tblChucVu.getValueAt(tblChucVu.getSelectedRow(),0).toString());
            if(JOptionPane.showConfirmDialog(this,"Bạn thật sự muốn xóa ?", "Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            sb.append("Xóa Thành Công");
            pc.executeUpdate();
            loadDataChucVu();
             }
            }
           
            else{
            sb.append("chỉ xóa được khi chức vụ này trống");
            }
             }
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
                }
            } catch (Exception ex) {
            System.out.println(ex.toString());
            }
    }//GEN-LAST:event_btnXoaChucVuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        StringBuilder sb = new StringBuilder();
        if(txtMaChucVu.getText().equals("")){
            sb.append("Hãy chọn chức vụ mà bạn muốn sửa ! \n");
        }
        else{
        if(txtTenChucVu.getText().equals("")){
            sb.append("Hãy nhập tên chức vụ bạn muốn sửa ! \n");
            txtTenChucVu.requestFocus();
        }
        else{
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement comm = conn.prepareStatement("update ChucVu set TenChucVu=? where MaChucVu=?");
            comm.setString(1,txtTenChucVu.getText());
            comm.setString(2,tblChucVu.getValueAt(tblChucVu.getSelectedRow(),0).toString());
            comm.executeUpdate();
            loadDataChucVu();
            loadDataChucVuNhanVien(txtMaChucVu.getText());
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        }
        } 
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMaChucVu.setText("");
        txtTenChucVu.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        int viTriDongVuaBam = tblChucVu.getSelectedRow();
        txtMaChucVu.setText(tblChucVu.getValueAt(viTriDongVuaBam, 0).toString());
        txtTenChucVu.setText(tblChucVu.getValueAt(viTriDongVuaBam, 1).toString());
        
        try {
            loadDataChucVuNhanVien(txtMaChucVu.getText());
        } catch (SQLException ex) {
            Logger.getLogger(ChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblChucVuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoaChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTable tblChucVuNhanVien;
    private javax.swing.JTextField txtMaChucVu;
    private javax.swing.JTextField txtTenChucVu;
    // End of variables declaration//GEN-END:variables
}
